project:
  type: website

  
website:
  title: "Producing Accessible Documents with LaTeX"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: general.qmd
        text: General Principles
      - href: workflows.qmd
        text: Workflows
      - href: latexcanvas.qmd
        text: LaTeX in Canvas
      - href: tagged-pdf.qmd
        text: Tagged PDFs
      - href: latexml.qmd
        text: Using LaTeXML
      - href: slides.qmd
        text: Slides
      - href: lualatex-guide.qmd
        text: LuaLaTeX Guide
      - href: alt-text.qmd
        text: ALT Text
      # - href: about.qmd
      #   text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    callout-appearance: simple
    callout-icon: false



