# General Principles for Accessibility

-   Whenever possible, use **structural elements** to structure your document. Use built-in headings and lists instead of relying on manual formatting on documents, slides, and tables. If available, start from a **template**.

-   **Don’t use color as the only way to communicate information.** If you are using colors, make sure to have **sufficient contrast**.

-   **Put alt text (text descriptions) on images and graphs.** ([More info](alt-text.html))

-   **Make sure all videos you are using have accurate captions and a transcript.** 


## Examples

### Use of structural elements in LaTeX

::: {.callout-important}
## Bad (not using latex structure)


```latex 
\texbf{1. My Section}
```
::: 


::: {.callout-tip}
## Good (using latex structure)

```latex
\section{My Section}

\subsection*{My unnumbered Subsection}
```
:::

or 

::: {.callout-important}
## Bad (not using predefined latex structure)

```latex
$\cdot$ Item 1
$\cdot$ Item 2
```
:::

::: {.callout-tip}
## Good (using predefined latex structure 'itemize')

```latex
\begin{itemize}
\item Item 1
\item Item 2
\end{itemize}
```
:::


### Use of colors in LaTeX


::: {.callout-important}
## Bad (not enough contrast)

```latex
\textcolor{red}{...}
\textcolor{green}{...}
```
:::

::: {.callout-tip}
## Good (sufficient contrast)

```latex
\textcolor{blue}{...}
\textcolor{teal}{...}
```
:::

Generally, the following LaTeX colors should have sufficient contrast over white background:

```latex
`blue`, `purple`, `teal`, `violet`, `black`, `darkgray`
```
