# Workflows to Produce Accessible Math Documents

## I just want to get some quick info into Canvas.

I have some short math content (e.g. solution to a homework problem) that I would like to get into Canvas, maybe as an announcement. Other than simple math formating for formulas (using `$ .. $` or `\[ .. \]`), it does not need any LaTeX.

**--->** Enter the text directly in the Canvas editor.


## I have LaTeX files that I compile as PDFs and post them on Canvas (or on other sites).

There are basically two options:

**--->** [Prepare your LaTeX source for tagging and produce a tagged PDF using `LuaLaTeX`.](tagged-pdf.qmd) <br>
**--->** Use `LaTeXML` to produce an html file instead of PDF.


## I have Beamer slides that I use for lectures and also post them on Canvas (or on other sites).



## I have an extensive set of lecture notes and would like to turn them into an interactive ebook hosted on the web.

You can try one of the modern, powerful, and versatile publishing frameworks, such as:

**--->** [PreText](https://pretextbook.org/) <br>
**--->** [Quarto](https://quarto.org)


## I have handwritten documents that I make available to my students online.